NetPing_modern/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NetPing_modern.ViewModels
{
    public class Cart
    {
        public String Name { get; set; }
        public String EMail { get; set; }
        public String Address { get; set; }
        public String Requisites { get; set; }
        public String Phone { get; set; }
        public String Shipping { get; set; }
        public IEnumerable<IDictionary<string, string>> Data { get; set; }
    }
}

NetPing_modern/Controllers/CartController.cs
using NetPing_modern.ViewModels;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using System.Net.Mime;
using System.Resources;
using Base32;

namespace NetPing_modern.Controllers
{
    public class CartController : Controller
    {
        //
        // GET: /Cart/
        public ActionResult Index()
        {
            return View();
        }

        public Boolean? SendCartMail(Cart cart)
        {
            try
            {
                var mail = new MailMessage();
                var client = new SmtpClient("smtpcorp.com", 2525) //Port 8025, 587 and 25 can also be used.
                {
                    Credentials = new NetworkCredential("sp@netping.ru", "JKWEop349f"),
                    EnableSsl = true
                };

                var timeStamp = DateTime.UtcNow.Subtract(new DateTime(2015, 6, 1)).TotalMilliseconds.ToString("R");

                var cartId = timeStamp.Contains(',') ? timeStamp.Remove(timeStamp.IndexOf(','), 1) : timeStamp;
                cartId = cartId.Contains('.') ? cartId.Remove(timeStamp.IndexOf('.'), 1) : cartId;

                mail.From = new MailAddress("shop@netping.ru");
                mail.To.Add("sales@netping.ru");
                mail.ReplyToList.Add(cart.EMail);
                mail.Subject = "Заказ № \"" + cartId + "\"";
                string items = "";
                var sum = 0;
                foreach (var cartitem in cart.Data)
                {
                    var itemrow = "";
                    var itemprice = Int32.Parse(((string)cartitem["price"]));
                    var itemcount = Int32.Parse(((string)cartitem["count"]));
                    itemrow = String.Format(@"<tr><td><img src='{0}' width=200/></td>
                        <td>{1}</td>
                        <td>{2} руб.</td>
                        <td>{3}</td>
                        <td>{4} руб.</td></tr>",
                            cartitem["photoURL"], cartitem["name"], cartitem["price"], cartitem["count"], itemprice * itemcount);
                    items += itemrow;
                    sum += itemprice * itemcount;
                }
                var cont = String.Format(@"<html><h2>{0}</h2>
                        <h2>Адрес доставки: {1}</h2>
                        <h2>Способ доставки: {2}</h2>
                        <h2>Телефон: {3}</h2>
                        <h2>Реквизиты: {4}</h2>
                        <h2>Сумма заказа: {5} руб.</h2>
                        <h2>Состав заказа</h2>
                        <table border=1 style='border: 1px solid #000; width: 100%; border-collapse: collapse'>
                        <tr><th></th><th>Наименование</th><th>Цена</th><th>Количество</th><th>Стоимость</th></tr>
                        {6}</table>
                        </html>", cart.Name, cart.Address, cart.Shipping, cart.Phone, cart.Requisites, sum, items);
                var htmlView = AlternateView.CreateAlternateViewFromString(cont, null, "text/html");
                mail.AlternateViews.Add(htmlView);
                client.Send(mail);



                mail.To.Clear();
                mail.To.Add(cart.EMail);
                mail.ReplyToList.Clear();
                mail.ReplyToList.Add("sales@netping.ru");

                cont = String.Format(@"<html><h2>Ваш заказ был получен, ждите ответа менеджера нашей компании</h2>
                        <h2>{0}</h2>
                        <h2>Адрес доставки: {1}</h2>
                        <h2>Способ доставки: {2}</h2>
                        <h2>Телефон: {3}</h2>
                        <h2>Реквизиты: {4}</h2>
                        <h2>Сумма заказа: {5} руб.</h2>
                        <h2>Состав заказа</h2>
                        <table border=1 style='border: 1px solid #000; width: 100%; border-collapse: collapse'>
                        <tr><th></th><th>Наименование</th><th>Цена</th><th>Количество</th><th>Стоимость</th></tr>
                        {6}</table>
                        </html>", cart.Name, cart.Address, cart.Shipping, cart.Phone, cart.Requisites, sum, items);
                htmlView = AlternateView.CreateAlternateViewFromString(cont, null, "text/html");
                mail.AlternateViews.Clear();
                mail.AlternateViews.Add(htmlView);
                client.Send(mail);


                /*

                                using (var wb = new WebClient())
                                {
                                    var data = new NameValueCollection();
                                    data["authuser"] = "sp@netping.ru";
                                    data["authpass"] = "NqIx8Fov";
                                    data["from"] = cart.EMail;
                                    data["subject"] = "Заказ";
                                    data["to"] = "sales@netping.ru";
                                    data["content"] = cart.Name + cart.Shipping + cart.Requisites + cart.Address;
                                    string items = "";
                                    var sum = 0;
                                    foreach (var cartitem in cart.Data)
                                    {
                                        var itemrow = "";
                                        var itemprice = Int32.Parse(((string)cartitem["price"]));
                                        var itemcount = Int32.Parse(((string)cartitem["count"]));
                                        itemrow = String.Format(@"<tr><td><img src='{0}' width=200/></td>
                                        <td>{1}</td>
                                        <td>{2} руб.</td>
                                        <td>{3}</td>
                                        <td>{4} руб.</td></tr>",
                                                cartitem["photoURL"], cartitem["name"], cartitem["price"], cartitem["count"], itemprice * itemcount);
                                        items += itemrow;
                                        sum += itemprice * itemcount;
                                    }

                                    data["html_content"] = String.Format(@"<html><h2>{0}</h2>
                                        <h2>Адрес доставки: {1}</h2>
                                        <h2>Способ доставки: {2}</h2>
                                        <h2>Телефон: {3}</h2>
                                        <h2>Реквизиты: {4}</h2>
                                        <h2>Сумма заказа: {5} руб.</h2>
                                        <h2>Состав заказа</h2>
                                        <table border=1 style='border: 1px solid #000; width: 100%; border-collapse: collapse'>
                                        <tr><th></th><th>Наименование</th><th>Цена</th><th>Количество</th><th>Стоимость</th></tr>
                                        {6}</table>
                                        </html>", cart.Name, cart.Address, cart.Shipping, cart.Phone, cart.Requisites, sum, items);
                                    var response = wb.UploadValues("https://api.turbo-smtp.com/api/mail/send", "POST", data);
                 */
                return null;
                //              }
            }
            catch (Exception e) //post failure
            {
                return false;
            }
        }
    }
}

NetPing_modern/Controllers/PreorderController.cs
using NetPing.DAL;
using NetPing.Models;
using NetPing_modern.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace NetPing_modern.Controllers
{
    public class PreorderController : Controller
    {
        private readonly IRepository _repository;

        public PreorderController(IRepository repository)
        {
            _repository = repository;
        }


        [HttpPost]
        public ActionResult SubmitPreorder(PreorderModel model)
        {
            var device = (Device)TempData["Device"];
            if (device != null)
            {
                SendPreorder(model, device);
                ViewData["Message"] = "Ваш предварительный заказ размещён";
                return Redirect("/products/" + device.Url);
            }
            else
                return Redirect("/development");
        }



        [HttpPost]
        public ActionResult SubmitPreorderAjax(PreorderModel model)
        {
            var device = (Device)TempData["Device"];
            if (device != null)
            {
                SendPreorder(model, device);
                ViewData["Message"] = "Ваш предварительный заказ размещён";
                return View("PreorderForm", new PreorderModel { Device = device });
            }
            else
                return Redirect("/development");
        }

        private void SendPreorder(PreorderModel model, Device device)
        {
            try
            {
                var mail = new MailMessage();
                var client = new SmtpClient("smtpcorp.com", 2525) //Port 8025, 587 and 25 can also be used.
                {
                    Credentials = new NetworkCredential("sp@netping.ru", "JKWEop349f"),
                    EnableSsl = true
                };

                var timeStamp = DateTime.UtcNow.Subtract(new DateTime(2015, 6, 1)).TotalMilliseconds.ToString("R");

                var cartId = timeStamp.Contains(',') ? timeStamp.Remove(timeStamp.IndexOf(','), 1) : timeStamp;
                cartId = cartId.Contains('.') ? cartId.Remove(timeStamp.IndexOf('.'), 1) : cartId;

                mail.From = new MailAddress("shop_dev@netping.ru");
                mail.To.Add("sales@netping.ru");
                mail.ReplyToList.Add(model.Email);
                mail.Subject = "DEV предварительный заказ № \"" + cartId + "\" на устройство \"" + device.Name.Name + "\"";
                var cont = String.Format(@"
                        <h2>Название устройства: {0}</h2>
                        <h2>Для: {1} {2}</h2>
                        <h2>Дата заказа: {3}</h2>
                        <h2>Комментарий: {4}</h2>
                        </html>", device.Name.Name, model.Name, model.Email, DateTime.Now.ToShortDateString(), model.Comment);
                var htmlView = AlternateView.CreateAlternateViewFromString(cont, null, "text/html");
                mail.AlternateViews.Add(htmlView);
                client.Send(mail);

                mail.To.Clear();
                mail.To.Add(model.Email);
                mail.ReplyToList.Clear();
                mail.ReplyToList.Add("sales@netping.ru");

                cont = String.Format(@"<html><h2>Ваш предварительный заказ размещён!</h2>
                        <h2>Название устройства: {0}</h2>
                        <h2>Для: {1} {2}</h2>
                        <h2>Дата заказа: {3}</h2>
                        <h2>Комментарий: {4}</h2>
                        </html>", device.Name.Name, model.Name, model.Email, DateTime.Now.ToShortDateString(), model.Comment);
                htmlView = AlternateView.CreateAlternateViewFromString(cont, null, "text/html");
                mail.AlternateViews.Clear();
                mail.AlternateViews.Add(htmlView);
                client.Send(mail);

            }
            catch (Exception e) //post failure
            {
                ViewData["Message"] = "При отправке заказа произошла ошибка";
            }
        }

    }
}

NetPing_modern/Views/Shared/Adaptive-Footer.cshtml
@{
    Layout = null;
}
@using NetPing_modern.Resources.Views.Shared
<div class="footer-container container-fluid">
    <div class="footer row">

        <div class="links col-xs-6">
            <ul>
                <li>
                    <a href="/products">@Footer.Tree_products</a>
                    <ul>
                        <li><a href="/products/monitoring-servernoj" class="footer_right_a">@Header.Category_monitoring</a></li>
                        <li><a href="/products/upravljaemye-rozetki-ip-pdu" class="footer_right_a">@Header.Category_power_control</a></li>
                        <li><a href="/products/monitoring-servernoj/sensors" class="footer_right_a">@Header.Category_sensors</a></li>
                        <li><a href="/products/monitoring-servernoj/accessories" class="footer_right_a">@Header.Category_access</a></li>
                    </ul>
                </li>
            </ul>
        </div>

        <div class="col-xs-6">
            <div class="links col-xs-6">
                <ul>
                    <li>
                        <a href="/buy">@Header.Menu_buy</a>
                        <ul>
                            <li><a href="/buy/dealers" class="footer_right_a">@Header.Menu_buy_partners</a></li>
                            <li><a href="/buy/partnership-how-to" class="footer_right_a">@Header.Menu_buy_partner_howto</a></li>
                        </ul>
                    </li>
                </ul>
                <ul>
                    <li>
                        <a href="/about">@Header.Menu_about</a>
                        <ul>
                            <li><a href="/contacts" class="footer_right_a">@Header.Menu_contacts</a></li>
                            <li><a href="/Blog/Category/News" class="footer_right_a">@Header.Menu_news</a></li>
                            <li><a href="/vacancy" class="footer_right_a">@Header.Menu_vacancy</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="links col-xs-6">
                <ul>
                    <li>
                        <a href="/support">@Header.Menu_support</a>
                        <ul>
                            <li><a href="/Blog/Category/FAQ" class="footer_right_a">@Header.Menu_faq</a></li>
                            <li><a href="/Blog/Category/Tutorial" class="footer_right_a">@Header.Menu_solutions</a></li>
                            @if (!NetpingHelpers.Helpers.IsCultureEng)
                            {
                                <li><a href="http://ideas.netping.ru/forums/213180-ideas" target="_blank" class="footer_right_a">Предложите новую идею для Netping!</a></li>
                            }
                        </ul>
                    </li>
                </ul>
                <ul>
                    <li><a href="/Blog">@Header.Menu_blog</a></li>
                </ul>
            </div>
        </div>


        <div class="col-xs-12">

            <div class="footer_left">
                <p>@Footer.Copyright</p>
            </div>

            <div class="footer_right">
                <!--
                    <ul>
                <li><a href="#" class="footer_right_a">@Footer.Privacy_policy</a></li>
                <li><a href="#" class="footer_right_a">@Footer.Terms_conditions</a></li>
                    </ul>
                    -->
            </div>
        </div>
    </div>
</div>

NetPing_modern/Views/Shared/Adaptive-Header.cshtml
@using NetpingHelpers
@{
    Layout = null;
}
@using NetPing_modern.Resources.Views.Shared

@if (NetpingHelpers.Helpers.IsCultureRus)
{
    <!-- Yandex.Metrika counter -->
    <script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
    <script type="text/javascript">
        try {
            var yaCounter169532 = new Ya.Metrika({
                id: 169532,
                webvisor: true,
                clickmap: true
            });
        } catch (e) { }
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/169532" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
}
@if (NetpingHelpers.Helpers.IsCultureEng)
{
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function () {
                try {
                    w.yaCounter25270505 = new Ya.Metrika({
                        id: 25270505,
                        webvisor: true,
                        clickmap: true,
                        trackLinks: true,
                        accurateTrackBounce: true
                    });
                } catch (e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/25270505" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
}

<div class="header contacts row">

    <div class="header_contacts clearfix">
        <div class="col-sm-4 col-md-3 col-lg-3 header_contacts_item">
            <div class="header_contacts_title">
                <!--<a href="/zakaz.aspx">@Header.Header_to_buy </a>-->
                @Header.Header_to_buy
            </div>
            <div class="header_content_border">
            </div>
            <div class="header_contacts_content">
                <span>@Header.Phone:</span>@Header.Header_phone<br />
                <span>e-mail:</span><a href="mailto:@Header.Header_email_sales">@Header.Header_email_sales</a>
            </div>
        </div>
        <div class="col-sm-4 col-md-3 col-lg-3 @(NetpingHelpers.Helpers.IsCultureEng ? "pull-right" : "") header_contacts_item">
            <div class="header_contacts_title">
                <!--<a href="/zakaz.aspx">@Header.Header_ask</a>-->
                @Header.Header_ask
            </div>
            <div class="header_content_border">
            </div>
            <div class="header_contacts_content">
                <span>@Header.Phone:</span>@Header.Header_phone<br />
                <span>e-mail:</span><a href="mailto:@Header.Header_email_support">@Header.Header_email_support</a>
            </div>
        </div>

        @if (!NetpingHelpers.Helpers.IsCultureEng)
        {
            <div class="col-sm-4 col-md-3  col-lg-3 cart">
                <span class="cart-icon"></span><span class="cart-text">@Header.Header_goods_in_basket</span><span class="cart-count">0</span>
            </div>
            <div class="col-md-3 col-lg-3 text-right hidden-sm hidden-xs">
                <div class="delivery-banner">
                    Доставка по России<br />
                    <span>бесплатно</span>
                </div>
            </div>
        }
    </div>

</div>
<div class="header main-header-wrapper row">

    <div class="main-header clearfix">

        <div class="logo-wrapper col-sm-12 col-md-5 col-lg-5">
            <a class="logo col-md-6 col-sm-4 col-sm-offset-1 col-md-offset-0" href="/">
                <img src="~/Content/Images/logo_text.png" alt="Netping logo" />
            </a>
            <div class="logo-text col-md-6 col-sm-5">
               @Html.Raw(Header.Logo_Title)
            </div>
            <div class="col-sm-3 text-right hidden-md hidden-lg">
                <div class="delivery-banner">
                    Доставка по России<br />
                    <span>бесплатно</span>
                </div>
            </div>
        </div>
        <div class="nav col-xs-8 col-sm-8 col-md-5 col-lg-5">
            <ul>
                <li class="nav_li">
                    <a class="@(Request.RawUrl.ToLower().Contains("/products") == true ? "nav_element active" : "nav_element")" href="/products/monitoring-servernoj">@Header.Products</a>
                    <div class="nav_element_border"></div>
                    <div class="abs">
                        <ul class="down_list">
                            <li class="item_list"><a href="/solutions/kommutatory-ethernet/re6enija-na-osnove-POE">@Header.Ready_solutions</a></li>
                            <li class="item_list"><a href="/products/monitoring-servernoj">@Header.Category_monitoring</a></li>
                            <li class="item_list"><a href="/products/upravljaemye-rozetki-ip-pdu">@Header.Category_power_control</a></li>
                            <li class="item_list"><a href="/products/kommutatory-ethernet">@Header.Category_switch</a></li>
                            <li class="item_list"><a href="/products/monitoring-servernoj/sensors">@Header.Category_sensors</a></li>
                            <li class="item_list"><a href="/products/monitoring-servernoj/accessories">@Header.Category_access</a></li>
                            <li class="item_list"><a href="/dev">@Header.Dev</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav_li">
                    <a class="@(Request.RawUrl.ToLower().Contains("/buy") == true ? "nav_element active" : "nav_element")" href="/buy"><b>@Header.Menu_buy</b></a>
                    <div class="nav_element_border"></div>
                    <div class="abs">
                        <ul class="down_list">
                            <li class="item_list"><a href="/buy">@Header.Menu_buy_directly</a></li>
                            <li class="item_list"><a href="/buy/dealers">@Header.Menu_buy_partners</a></li>
                            <li class="item_list"><a href="/buy/partnership-how-to">@Header.Menu_buy_partner_howto</a></li>
                        </ul>
                    </div>
                </li>
                <li class="nav_li">
                    <a class="@(Request.RawUrl.ToLower().Contains("/about") == true ? "nav_element active" : "nav_element")" href="/about">@Header.Menu_about</a>
                    <div class="nav_element_border"></div>
                    <div class="abs">
                        <ul class="down_list">
                            <li class="item_list"><a href="/contacts">@Header.Menu_contacts</a></li>
                            <li class="item_list"><a href="/Blog/Category/News">@Header.Menu_news</a></li>
                            @if (!NetpingHelpers.Helpers.IsCultureEng)
                            {
                                <li class="item_list"><a href="/vacancy">@Header.Menu_vacancy</a></li> }
                        </ul>
                    </div>
                </li>

                <!--
                <li class="nav_li">
                    <a class=@(Request.RawUrl.ToLower().Contains("/contacts") == true ? "nav_element active" : "nav_element") href="/contacts">@Header.Menu_contacts</a>
                    <div class="nav_element_border"></div>
                </li>
                    -->
                <li class="nav_li">
                    <a class="@(Request.RawUrl.ToLower().Contains("/support") == true ? "nav_element active" : "nav_element")" href="/support">@Header.Menu_support</a>
                    <div class="nav_element_border"></div>
                    <div class="abs">
                        <ul class="down_list">
                            <li class="item_list"><a href="/Blog/Category/FAQ">@Header.Menu_faq</a></li>
                            <li class="item_list"><a href="/Blog/Category/Tutorial">@Header.Menu_solutions</a></li>
                            @if (!NetpingHelpers.Helpers.IsCultureEng)
                            {
                                <li class="item_list"><a href="http://ideas.netping.ru/forums/213180-ideas" target="_blank">Предложите новую идею для Netping!</a></li>
                            }
                            @*<li><div class="clear"></div></li>*@
                        </ul>
                    </div>
                </li>
                <li class="nav_li">
                    <a class="@(Request.RawUrl.ToLower().Contains("/Blog") == true ? "nav_element active" : "nav_element")" href="/Blog">@Header.Menu_blog</a>
                    <div class="nav_element_border"></div>
                </li>



            </ul>

        </div>
        <form class="search" name="search" action="http://www.google.com/cse" target="_blank">
            <div class="search col-xs-4 col-sm-3 col-md-2 col-lg-2 pull-right">
                <input type="text" placeholder="Поиск по сайту" name="q" />
                <input type="hidden" name="cx" value="006534849235046585456:eqktuqsoi58" />
                <input name="ie" type="hidden" value="UTF-8" />
                <input type="submit" value="Найти" />
            </div>
        </form>
    </div>
    <div class="clear"></div>
</div>

NetPing_modern/Views/Shared/Adaptive_master.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <link href="/Content/Images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="~/Content/Themes/reset.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Themes/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Themes/adaptive.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Content/Themes/adaptive-header-footer.css">
    @RenderSection("Head_Css", false)
    @*<link rel="stylesheet" type="text/css" href="~/Content/Themes/responsiveslides.css">*@
    @*<link rel="stylesheet" type="text/css" href="~/Content/Themes/slide.css">*@
    <link rel='stylesheet' type='text/css' href='~/Content/Themes/cart/cart.css'>
    @if (NetpingHelpers.Helpers.IsCultureEng)
    {
        <link rel="stylesheet" type="text/css" href="~/Content/Themes/shutter_eng.css">
    }
    else
    {
        <link rel="stylesheet" type="text/css" href="~/Content/Themes/shutter.css">
    }
    <link href="~/Content/Themes/tinycarousel.css" rel="stylesheet" />
    <script src="~/Content/JavaScript/jquery1.8.3min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/JavaScript/modernizr.js"></script>
    <script src="~/Content/JavaScript/jquery.siblingsshutter.js"></script>
    <script src="~/Content/JavaScript/main.js"></script>
</head>
<body>
    <div class="container-fluid header-container">
        @RenderPage("../Shared/Adaptive-Header.cshtml")
    </div>
    @RenderBody()


    @RenderPage("../Shared/Adaptive-Footer.cshtml")
    <div class="overlay"></div>
    <div class="popup" id="popup1"></div>
    <script src="~/Content/JavaScript/ProductItem.js" type="text/javascript"> </script>
    <script src="~/Content/JavaScript/jquery.tinycarousel.min.js"></script>
    <script src="~/Content/JavaScript/responsiveslides.min.js" type="text/javascript"> </script>
    <script src="~/Content/JavaScript/slider1.js" type="text/javascript"> </script>
    @RenderPage("../Shared/Cart.cshtml")
</body>
</html>

NetPing_modern/Views/Shared/Korzina.cshtml
@{
    Layout = null;
}
<link rel="stylesheet" type="text/css" href="~/Content/Themes/korzina.css">


<div style="display: none">
    <div class="shopPopupItem" id="korizinaItemShablon">
        <p class="hiddenID"></p>
        <div class="shopItemImgContainer left">
            <img class="shopPopupItemImg" src="" alt="" />
        </div>
        <div class="shopItemC2 left">
            <p class="shopItemName"></p>
            <p class="shopItemPriceP left">Price for one item  </p>
            <p class="shopItemPrice left"></p>
            <p class="left">rub</p>
            <div>
                <p class="shopItemCountP left">Count</p>
                <input type="number" class="shopItemCountInput left" value="" />
            </div>
            <div style="clear: both">
                <p class="shopItemPriceItogoP left">Price Itogo</p>
                <p class="shopItemPriceItogo left"></p>
            </div>
            <div style="clear: both">
                <input type="button" class="removeProduct left" value="remove" />
            </div>
        </div>
    </div>
</div>

<div class="overlayKorzina"></div>
<div id="korzinaPopup">
    <div id="korinaAbout" class="k1">
        <div id="userInfo">
            <p>ФИО</p>
            <input type="text" id="FIOK"/>
            <p>Email </p>
            <input type="text" id="emailK"/>
            <p>адрес доставки</p>
            <input type="text" id="addressK"/>
            <p>реквизиты для выстваления счёта (для юр. лиц) </p>
            <input type="text" id="rekvizitiK"/>
            <p>способ доставки</p>
            <input type="radio" value="EMS почта России" name="sposobDostavki" />
            <input type="radio" value="Гарантпост" name="sposobDostavki" />
        </div>
    </div>
    <div id="korzinaItems" class="k1"></div>
    <input type="button" class="cartPopupButton" id="clearCartButton" value="Clear Cart" />
    <input type="button" class="cartPopupButton" id="backCartButton" value="Back" style="display: none;"/>
    <input type="button" class="cartPopupButton" id="continueCartButton" value="Continue" />
    <input type="button" class="cartPopupButton" id="sendDataCartButton" value="Send Email" style="display: none;" />
</div>

<script src="~/Content/JavaScript/jquery.cookies.2.2.0.min.js" type="text/javascript"> </script>
<script src="~/Content/JavaScript/korzina.js" type="text/javascript"> </script>

NetPing_modern/Views/Shared/PreorderForm.cshtml
@model NetPing_modern.Models.PreorderModel
@using NetPing_modern.Resources.Views.Catalog;

@{
    TempData["Device"] = Model.Device;
}

<div class="message"> @ViewData["Message"]</div>

@using (Ajax.BeginForm("SubmitPreorder", "Preorder", new { }, new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "Post",
    UpdateTargetId = "preorder-form",
    Url = Url.Action("SubmitPreorderAjax", "Preorder"),
    OnSuccess = "SuccessFunction"
}, new { id = "preorder-form" }))
{
    @Html.TextBoxFor(model => Model.Name, new { placeholder = Dev.Preorder_form_name_placeholder })
    @*<input type="text" name="name" placeholder="@Dev.Preorder_form_name_placeholder" />*@
    <div class="preorder-email">
        @Html.TextBoxFor(model => Model.Email, new { placeholder = Dev.Preorder_form_email_placeholder })
        @*<input type="email" name="email" placeholder="@Dev.Preorder_form_email_placeholder" />*@
    </div>
    @Html.TextAreaFor(model => Model.Comment, new { placeholder = Dev.Preorder_form_comment_placeholder, rows = 3 })
    @*<textarea name="comment" placeholder="@Dev.Preorder_form_comment_placeholder" rows="3"></textarea>*@
    <input type="submit" value="@Dev.Preorder_form_submit" class="preorder-submit" />
}

<script>
    function SuccessFunction() {
        alert("@ViewData["Message"]");
        $('#preorder-form').find("input[type=text], textarea").val("");
    }
</script>